version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5289:8080"  # Swagger ve proxy dış erişim
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hotelbooking-network

networks:
  hotelbooking-network:
    external: true
