services:
  auth-user-service:
    container_name: auth-user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5060:80"  # Dockerfile'da sadece 80 expose edilmiş
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-auth
    ports:
      - "5672:5672"   # Uygulama bağlantısı
      - "15672:15672" # RabbitMQ yönetim paneli
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
