version: '3.8'

services:
  auth-user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-user-service
    ports:
      - "5045:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=AuthUserDb;User Id=LastUser;Password=lastuser123;TrustServerCertificate=True;
      - ConnectionStrings__RedisConnection=redis:6379
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__QueueName=userQueue
      - AzureAd__Instance=https://login.microsoftonline.com/
      - AzureAd__Domain=hotelbookingext.onmicrosoft.com
      - AzureAd__TenantId=1649cae6-96a4-42a7-9f82-3e339752b193
      - AzureAd__ClientId=f6bc9acf-c194-4221-8145-2afc6775bd46
      - AzureAd__ClientSecret=Dxr8Q~TGqx_AadxPCzpHBWU3z-C5eyf~Vkdt_a_7
      - AzureAd__CallbackPath=/signin-oidc
      - AzureAd__Scopes=api://f6bc9acf-c194-4221-8145-2afc6775bd46/access_as_user
      - AzureAd__Audience=api://f6bc9acf-c194-4221-8145-2afc6775bd46
    depends_on:
      - mssql
      - redis
      - rabbitmq
    networks:
      - hotelbooking-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=saUser.123
      - MSSQL_PID=Express
      - MSSQL_AUTHENTICATION_MODE=Mixed
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - hotelbooking-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hotelbooking-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - hotelbooking-network

networks:
  hotelbooking-network:
    name: hotelbooking-network

volumes:
  mssql_data:
