# version artık gerekli değil, kaldırıldı
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/hotel_db
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - microservices-network  # Network'e eklendi
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network  # Network'e eklendi
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network  # Network'e eklendi

# Network tanımı eklendi
networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data: