spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

rabbitmq:
  exchange:
    name: booking.exchange

  routing:
    bookingCreated: booking.created # BookingCreatedEvent (→ Payment)
    cancelled: booking.cancelled # ReservationCancelledEvent (→ Audit/Logging)
    reservationCreated: booking.reservation.created # ReservationCreatedEvent (→ Hotel)
    confirmed: booking.confirmed # ReservationConfirmedEvent (→ Notification/UI)

  queue:
    bookingCreated: booking.created.queue # Booking Created Event kuyruğu
    bookingCancelled: booking.cancelled.queue # Cancel Event kuyruğu
    paymentSucceeded: payment.success.queue # Payment Success kuyruğu
    paymentFailed: payment.failed.queue # Payment Failed kuyruğu
    roomFailed: hotel.room.failed.queue # Room Availability Failed kuyruğu
